---
- hosts: droplets
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started
      
---

- hosts: AppServer

  become: yes

  tasks:

  - name: Installs nginx web server

    apt:

      name: nginx

      state: present

      update_cache: true

    notify:

    - start nginx

  handlers:

  - name: start nginx

    service:

      name: nginx

      state: present      
